name: Shared Actions Example

on:
  workflow_dispatch:

jobs:
  checkout-repo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Check-out repo under $GITHUB_WORKSPACE, so workflow can access it

      - run: src/create_occurrence.sh testfiles/tc00/event.csv testfiles/tc00/asv-table.csv

#      - run: if [ $(diff occurrence.csv testfiles/tc00/occurrence.csv | wc -l) -ge 0 ]; then exit 2; fi
      - run: ls occurrence.csv

      - run: diff occurrence.csv testfiles/tc00/occurrence.csv > diff.out

      - run: if [ ! -s diff.out ]; then cat diff.out; exit 2; else exit 0; fi
